# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2622eaec426879b72baee4b2b65f7e6edaede33f3ad58e7d7a121136e4bb26fbbda3f933c6ce6c7f331ad6ae7e71878f2a3c6dc164b8c27e153a12a9624c1b1

test:
  secret_key_base: 70ec5e3d369b114677e005d7bbe594c0014097fe89c6527eb8093e16a1562d1b85875e476306eaffbda89471f36646fbb16bbbd53090ab00bfd347df53bdb4b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
